// Generated by scripts/sync-docs-navigation.mjs. Do not edit directly.
const sidebars = {
  "documentationSidebar": [
    {
      "type": "category",
      "label": "Application surfaces",
      "link": {
        "type": "doc",
        "id": "surfaces/index"
      },
      "items": [
        {
          "type": "category",
          "label": "Project capabilities",
          "link": {
            "type": "doc",
            "id": "surfaces/project-capabilities"
          },
          "items": []
        },
        {
          "type": "category",
          "label": "Assets",
          "link": {
            "type": "doc",
            "id": "surfaces/assets"
          },
          "items": []
        },
        {
          "type": "category",
          "label": "Accounts",
          "link": {
            "type": "doc",
            "id": "surfaces/accounts"
          },
          "items": []
        },
        {
          "type": "category",
          "label": "Universes",
          "link": {
            "type": "doc",
            "id": "surfaces/universes"
          },
          "items": []
        },
        {
          "type": "category",
          "label": "Bars",
          "link": {
            "type": "doc",
            "id": "surfaces/bars"
          },
          "items": []
        }
      ]
    },
    {
      "type": "category",
      "label": "Technical documentation",
      "link": {
        "type": "doc",
        "id": "technical/index"
      },
      "items": [
        {
          "type": "category",
          "label": "Frontend implementation plan",
          "link": {
            "type": "doc",
            "id": "technical/frontend-implementation-plan"
          },
          "items": []
        },
        {
          "type": "category",
          "label": "Architecture",
          "link": {
            "type": "doc",
            "id": "technical/architecture"
          },
          "items": []
        },
        {
          "type": "category",
          "label": "Testing and verification",
          "link": {
            "type": "doc",
            "id": "technical/testing"
          },
          "items": []
        },
        {
          "type": "category",
          "label": "Deployment",
          "link": {
            "type": "doc",
            "id": "technical/deployment"
          },
          "items": []
        }
      ]
    }
  ]
};

export default sidebars;
